### ISSUE TITLE
Hawaii fails to start on Sabayon Linux

### ISSUE THREAD

**Issue by fusion809** [hawaii-desktop/hawaii-shell#194]
Hi,

I compiled and installed Hawaii (specifically hawaii-shell, hawaii-baseapps, libhawaii, greenisland, hawaii-icon-theme, hawaii-wallpapers, hawaii widget styles and hawaii system preferences) without any errors, after I resolved a little dependency issue with greenisland (see [Unix & Linux SE](http://unix.stackexchange.com/questions/240403/which-gentoo-package-provides-qt5compositorconfig-cmake) for details) but now when I run `hawaii-session` from tty2 I am told I am missing some module called `eglfs`? I would provide the exact error message here, if I could, but tty2 is without a clipboard, hence I cannot copy-paste the error. 

Thanks for your time,
Brenton

**Comment by plfiorini** [comment]
eglfs is the EGL full screen QPA plugin that allows Qt applications such as Hawaii to run full screen without another windowing system available.

Qt needs to be built with EGL and the eglfs plugin, however in order to provide extra features I forked the plugin in the greenisland repository (which where the lower level stuff for Hawaii goes).

So greenisland 0.6.92 has got its own plugin and hawaii-session should automatically pick it up.
