### ISSUE TITLE
Hawaii doesn't start from tty

### ISSUE THREAD

**Issue by CheeryLee** [hawaii-desktop/hawaii-shell#220]
Arch Linux 64 bit. Kernel 4.4.5-1. Hawaii from AUR. 

When I try to start shell from tty by launch 'starthawaii' or 'hawaii-shell' It will not run without already launched X-session (QXcbConnetcion couldn't connect to display). But when X is running Hawaii runs through the window.
A similar problem with GreenIsland. 

How to resolve? 
##

**Comment by Astianos** [comment]
@plfiorini We are building the system and from the base is by tty we are installing the needed packages and we have already installed hawaii-desktop, but there is a problem

**Comment by Astianos** [comment]
the problem is solved by enabling the KMS option, and enabling support for card videos using this link.

https://wiki.archlinux.org/index.php/Kernel_mode_setting

but exist new problem is

When you run the command, hawaii-session provides the following output.

greenisland.launcher: Mode: "eglfs"
greenisland.launcher: Haedware: "drm"
greenisland.launcher: libinput: true
greenisland.launcher: Running: /usr/bin/hawaii --wayland-socket-name greenisland-seat0

QML debugging is enable. Only use this in a safe enviroment.
greenisland.qpa-deviceintegration: EGL device integration plugin lookup paths: /usr/lib/qt/plugins /usr/bin
greenisland.gpa.deviceintegration: Preferred EGL device integration based on the haedware configuration: "kms"
greenisland.qpa.deviceintegration: Using "kms" EGL device integraton
greenisland.qpa.kms: Found the following video devices:

Could not find DRM device
Aborted

Thanks

**Comment by plfiorini** [comment]
udev doesn't find any DRM device, this probably means you didn't build any driver with your kernel or for some reason the kernel module is not loaded.

Check with lsmod if the driver for your hardware is loaded.

It is also advised to double check with weston. Does it have the same problem?

**Comment by plfiorini** [comment]
Also check the kernel command line for options that might disable kms.

My advice is to start with a known good kernel configuration, install the Arch kernel package and boot with it.

**Comment by Astianos** [comment]
With weston the same problem occurs, although the configuration we are doing it with virtualbox will return to do the construction and testing with qemu. Since we read that virtualbox does not support Wayland.

Thank you plfiorini a hug.

**Comment by plfiorini** [comment]
@CheeryLee Can you capture the output and share it with us via pastebin.com?

```sh
hawaii-session &> log
```
